class StaticEnv
  JURNAL_BASE_PATH = ENV['JURNAL_BASE_PATH'] + "/partner/core/api/v1/"
  MAIL_FROM        = ENV['MAIL_FROM']
  LOAN_MAIL        = ENV['LOAN_MAIL']
  LOAN_MAIL_PASS   = ENV['LOAN_MAIL_PASS']
  JURNAL_MAIL      = ENV['JURNAL_MAIL']
  LOAN_NOTIF_MAIL  = ENV['LOAN_NOTIF_MAIL']
end